.automation/create-index-page.sh
.github/workflows/build.yml

Fix publishing documentation

---

.github/CODEOWNERS
.github/workflows/build.yml

Fix documentation generation 2

---

.automation/create-index-page.sh
.github/workflows/build.yml

Fix documentation generation 3

---

.github/workflows/build.yml

Debugging documentation generation issues

---

.github/workflows/build.yml

Fix publishing documentation 6

---

.github/workflows/build.yml

Add GITHUB_TOKEN write permissions to repository.

Add token permissions

---

src/main/java/types/CpuPinningPolicy.java

The dedicated CPU policy has been added to oVirt, let's support it in REST API too.

Add Dedicated cpu policy to CpuPinningPolicy

---

pom.xml

Remove gerrit references from pom.xml

---

src/main/java/types/Display.java

Change-Id: I18cc4b6b3cc43541f892f112f12f4e43e87c0839
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1944834

Added Display.disconnectActionDelay

---

src/main/java/services/DiskService.java

Remove whitespace from DiskService

---

src/main/java/types/CloudInit.java
src/main/java/types/Cluster.java
src/main/java/types/Disk.java
src/main/java/types/ExternalStatus.java
src/main/java/types/Host.java
src/main/java/types/HostNic.java
src/main/java/types/ImageTransfer.java
src/main/java/types/ImageTransferDirection.java
src/main/java/types/ImageTransferPhase.java
src/main/java/types/ImageTransferTimeoutPolicy.java
src/main/java/types/Initialization.java
src/main/java/types/MemoryPolicy.java
src/main/java/types/NetworkFilterParameter.java
src/main/java/types/OpenStackNetworkProvider.java
src/main/java/types/OperatingSystem.java
src/main/java/types/OsType.java
src/main/java/types/Qos.java
src/main/java/types/QosType.java
src/main/java/types/RegistrationVnicProfileMapping.java
src/main/java/types/StorageDomain.java
src/main/java/types/StorageDomainType.java
src/main/java/types/StorageFormat.java
src/main/java/types/User.java
src/main/java/types/VmBase.java
src/main/java/types/VnicProfile.java

Updating xrefs in Types

---

README.md

README: add COPR build status badge

---

src/main/java/types/MigrationOptions.java
src/main/java/types/ParallelMigrationsPolicy.java

Bug-Url: https://bugzilla.redhat.com/2078500

Add parallel migration connections

---

pom.xml

Temp revert 4.5.8 release

---

pom.xml

Fix developerConnection URL

---

CHANGES.adoc
pom.xml

- Update CHANGES.adoc for release 4.5.10
- [maven-release-plugin] prepare release 4.5.10
- [maven-release-plugin] prepare for next development iteration

rel 4.5.10

---

pom.xml

Revert commit "Fix developerConnection URL" with id
d520ce676496d192fa6f88dc5e7c9fbd96f1eac2

Revert: Fix developerConnection URL

---

src/main/java/types/OperatingSystemInfo.java
src/main/java/types/TpmSupport.java

Expose via REST TPM support provided/required by the OS.
Reference-Url: https://github.com/oVirt/ovirt-web-ui/issues/1596

Add TpmSupport to OperatingSystemInfo

---

src/main/java/003-CommonConcepts.adoc
src/main/java/004-QuickStartExample.adoc
src/main/java/A02-ChangesInV4.adoc
src/main/java/services/DiskAttachmentsService.java
src/main/java/services/DisksService.java
src/main/java/services/VmCdromService.java
src/main/java/types/Cluster.java
src/main/java/types/Device.java

Cherry-picked from 8af26f1857bb1a583330fcb12d45525c80ddea32
xref:https://github.com/oVirt/ovirt-engine-api-model/pull/86

Cherrypicking changes

---

src/main/java/services/DiskService.java

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2108182

Add note about sparsifying disk after conversion

---

pom.xml

bump to metamodel 1.3.10

---

pom.xml

bump version to 4.6.0-SNAPSHOT

---

.automation/build-srpm.sh

Move build date before git hash for nightly builds

---

.github/workflows/build.yml

Enable CS9 builds

---

.automation/build-srpm.sh

Fix using git hash in COPR builds

---

.github/workflows/build.yml

Remove CentOS 8 from the pipeline and update our github actions.

ci: remove c8s and update github actions
