oVirt/ovirt-engine-api-model

- src/main/java/001-Introduction.adoc
- src/main/java/types/Initialization.java
Updated files to remove references to the Ruby SDK based on https://bugzilla.redhat.com/show_bug.cgi?id=2020168.
> BZ2020168 - Removed references to Ruby SDK

- src/main/java/services/HostCpuUnitsService.java
- src/main/java/services/HostService.java
- src/main/java/types/Host.java
- src/main/java/types/HostCpuUnit.java
Introduce the possibility to retrieve the list of the host's physical CPUs with the current pinning status.
> Introduce host CPU units details

- src/main/java/types/Backup.java
This field will contain the information of the snapshot created for hybrid backup, will remain empty if the backup is not hybrid.
Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>
> Add snapshot field to backup

- src/main/java/services/VmPoolService.java
- src/main/java/services/VmPoolsService.java
- src/main/java/services/VmsService.java
The 'seal' parameter is added to VM creation and to VM Pool creation and
update, when VMs may be created for the pool.
Change-Id: I46d9763fb909643a622a946b72b30d6d73659243
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>
Bug-Url: https://bugzilla.redhat.com/2054681
> Add 'seal' parameter for created VMs

- src/main/java/services/TemplateMediatedDeviceService.java
- src/main/java/services/TemplateMediatedDevicesService.java
- src/main/java/services/TemplateService.java
- src/main/java/services/VmMediatedDeviceService.java
- src/main/java/services/VmMediatedDevicesService.java
- src/main/java/services/VmService.java
- src/main/java/types/Template.java
- src/main/java/types/Vm.java
- src/main/java/types/VmMediatedDevice.java
Support for vGPU mediated devices was previously handled by VM custom
properties.  We move from using custom properties for that purpose to
using fake VM devices.  Since there is no general support in the API
to handle VM devices, this patch introduces a special API entities for
dealing with mediated devices, similarly to graphics console
configuration.
> api-model: Add mediated devices

- src/main/java/services/ClusterService.java
- src/main/java/types/Cluster.java
- src/main/java/types/ClusterUpgradeAction.java
- Add `UPDATE_PROGRESS` action to `ClusterUpgradeAction` so the ansible role can directly report upgrade progress.
- Add `upgradeInProgress`, `upgradeProgress` and `upgradeCorrelationId` to the `Cluster` so the status and progress of an upgrade can be checked.
Bug-Url: https://bugzilla.redhat.com/2040474
Needed for: https://github.com/oVirt/ovirt-engine/pull/170
> Add upgrade progress tracking for Clusters

- src/main/java/services/VmBackupsService.java
This flag is essentially a feature toggle for hybrid backup. By default use_active=False and a snapshot will be created. Otherwise, no snapshots will be used and backup will be performed using the active volume.
> backup: introduce the use_active flag

- .github/workflows/build.yml
1. Use generated documentation from CentOS Stream 8 build artifacts
2. Fix generated documentation path in build artifacts
> Fix populating documentation

- src/main/java/001-Introduction.adoc
- src/main/java/002-AuthenticationAndSecurity.adoc
- src/main/java/003-CommonConcepts.adoc
- src/main/java/004-QuickStartExample.adoc
- src/main/java/A01-PrimitiveTypes.adoc
- src/main/java/A02-ChangesInV4.adoc
Updating Asciidoc cross-refs and some tags in the top level .adoc files.
Fixed header levels to comply with current Asciidoc formatting conventions.
> Fixing cross refs

- .copr/Makefile
- ovirt-engine-api-model.spec.in
Dropping missing packages in f35 build root allowing to build on copr.
Signed-off-by: Sandro Bonazzola <<sbonazzo@redhat.com>>
> copr: allow to build src.rpm in fc35 buildroot

- ovirt-engine-api-model.spec.in
Turn off automatic generation of RPM requires, because on COPR we have
an old version of xmvn, which is not able to properly generate
dependency on 'java-11-openjdk-headless >= 1:11.0.0' and instead it
generate dependency on non-existent package 'java-headless >= 1:11'
> Define RPM requirements manually

- src/main/java/types/CpuPinningPolicy.java
This patch introduces the new isolate threads policy.
It acts as dedicated policy, but each virtual CPU (a virtual thread)
will get a physical core to itself.
Change-Id: Iededc6e18b536889cf2da5dcc9a3c6dcb554a268
Bug-Url: https://bugzilla.redhat.com/1782077
Signed-off-by: Liran Rotenberg <lrotenbe@redhat.com>
> Introduce isolate threads CpuPinningPolicy

- src/main/java/003-CommonConcepts.adoc
Sandro removed 2 IDs in https://github.com/oVirt/ovirt-site/pull/2885.
This PR fixes the problem of duplicate anchor IDs in the generated model.adoc file.
> Updating 2 anchor IDs to eliminate duplication

- src/main/java/types/VnicProfile.java
Hot linking vNICs with a profile that has port mirroring enabled is not
supported, and not hot plugging.
Change-Id: I371ad695674a63499e63b18ba771a25fb0df8afc
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
> networking - fix typo in port mirroring limitations

- ovirt-engine-api-model.spec.in
docs generation is performed before generating the src.rpm
so there's no need to require those deps for rpm build.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
> spec: drop deps on asciidoctor

- src/main/java/002-AuthenticationAndSecurity.adoc
- src/main/java/003-CommonConcepts.adoc
- src/main/java/004-QuickStartExample.adoc
- src/main/java/A01-PrimitiveTypes.adoc
- src/main/java/A02-ChangesInV4.adoc
Changes:
- Changed duplicate anchor IDs that were breaking the Asciidoc build
- Removed "assembly" content tag from 002 and later parts because the asciidoc files are used to generate a single file. So only the first "assembly" tag needs to appear.
@oliel Please review.
> Fixing duplicate ID, removing assembly content tag

- src/main/java/services/SystemOptionService.java
- src/main/java/types/Cluster.java
- src/main/java/types/VmBase.java
Documentation to SystemOptionService is changed to use MigrationPolicies
option as an example instead of non-existing MigrationPoliciesSupported
option.
Change-Id: Ie0c2eadf855758b522f39b35bd756c943701d024
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>
> Updated documentation to SystemOptionService

- src/main/java/types/VmPool.java
VmPool.display attribute is not used by the backend code. It was added
by mistake and should be deprecated to avoid confusion.
Change-Id: Idc06374e8654c0cab10a120004e7db69207a335b
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>
> Deprecate VmPool.display attribute

- src/main/java/services/ImageTransferService.java
- src/main/java/types/ImageTransferPhase.java
Changed the ovirt-imageio-proxy and ovirt-imageio-daemon to ovirt-imageio per https://bugzilla.redhat.com/show_bug.cgi?id=2042401.
> BZ2042401 - Image I/O Proxy is replaced by ovirt-imageio

- ovirt-engine-api-model.spec.in
- pom.xml
Use DocTool from metamodel to generate documentation, which was
introduced in 1.3.8 release
> Use DocTool from metamodel to generate documentation

- ovirt-engine-api-model.spec.in
Adds build dependency to maven to pass build on COPR for EL8,
which uses old xmvn version
> Add build dependency to maven

- .github/workflows/build.yml
Switch to the cs9 documentation artifact as the cs8 one is not build anymore.
> ci: switch generated-documentation-cs8 to cs9

- .automation/build-srpm.sh
- ovirt-engine-api-model.spec.in
Depend on maven-openjdk11 version of Maven to be able to build on Copr which uses another default Java version and set JAVA_HOME to java11.
> build: depend on maven-openjdk11 + set JAVA_HOME

- .github/workflows/build.yml
We want to publish snapshot releases to ossrh so we can use it in snapshot builds of ovirt-engine etc.
> ci: publish snapshot release to ossrh

- .github/workflows/build.yml
This is needed to build ovirt-engine.
> ci: also publish javadoc snapshot

- .github/workflows/build.yml
PR's from external repositories don't have access to secrets. Skip configuration of settings.xml on PR's as this is useless anyway.
> ci: don't configure settings.xml on PR

- src/main/java/types/LogicalUnit.java
This is necessary for the ISCI multipath status.
> Added activePaths to LogicalUnit model

- src/main/java/types/OperatingSystem.java
added a new description field to OperatingSystem to make a more specific description of the OS that runs on a certain host available.
Fixes issue: https://github.com/oVirt/ovirt-engine-api-model/issues/105
> api: add description string field to OperatingSystem
